# Generated by Django 5.1.4 on 2025-02-24 11:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('categoria', models.CharField(choices=[('Cervezas', 'Cervezas'), ('Bebida/Refresco', 'Bebida/Refresco'), ('Copa Vino', 'Copa Vino'), ('Botellas Vino', 'Botellas Vino'), ('Fuera de Carta', 'Fuera de Carta'), ('Pan', 'Pan'), ('Tapas o ½ Ración', 'Tapas o ½ Ración'), ('Entrantes', 'Entrantes'), ('Pescados', 'Pescados'), ('Carnes Ibéricas', 'Carnes Ibéricas'), ('Carnes Ternera', 'Carnes Ternera'), ('Bocadillos', 'Bocadillos'), ('Postres', 'Postres'), ('Cafés', 'Cafés'), ('Bebidas Alcohólicas', 'Bebidas Alcohólicas'), ('Desayunos', 'Desayunos'), ('Oferta del día', 'Oferta del día')], max_length=50)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=6)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='productos/')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mesa', models.CharField(max_length=50)),
                ('numero_clientes', models.PositiveIntegerField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('cerrado', models.BooleanField(default=False)),
                ('camarero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PedidoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('nota', models.TextField(blank=True, null=True)),
                ('tipo_plato', models.CharField(blank=True, choices=[('Entrante', 'Entrante'), ('Primer plato', 'Primer plato'), ('Segundo plato', 'Segundo plato')], max_length=20, null=True)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='tapAppGestion.pedido')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tapAppGestion.producto')),
            ],
        ),
    ]
