# Generated by Django 5.1.4 on 2025-03-02 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tapAppGestion', '0004_producto_permite_cajas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='permite_cajas',
        ),
    ]
