# Generated by Django 5.1.4 on 2025-03-02 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tapAppGestion', '0005_remove_producto_permite_cajas'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='permite_cajas',
            field=models.BooleanField(default=False),
        ),
    ]
