# Generated by Django 5.1.4 on 2025-03-05 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tapAppGestion', '0007_remove_producto_permite_cajas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='camarero',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='cerrado',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='fecha',
        ),
        migrations.DeleteModel(
            name='PedidoItem',
        ),
    ]
