# Generated by Django 5.1.4 on 2025-03-05 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tapAppGestion', '0008_registrohorario'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrohorario',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
