# Generated by Django 5.1.4 on 2025-03-19 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tapAppGestion', '0012_pedido_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='fecha_cierre',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
