# Generated by Django 5.1.4 on 2025-03-21 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tapAppGestion', '0009_registrohorario_activo'),
        ('tapAppGestion', '0013_pedido_fecha_cierre'),
    ]

    operations = [
    ]
