# Generated by Django 5.1.4 on 2025-03-21 18:11

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tapAppGestion', '0014_merge_20250321_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='es_barril',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='producto',
            name='litros_disponibles',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6),
        ),
        migrations.AddField(
            model_name='producto',
            name='litros_por_unidad',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=4),
        ),
    ]
