# Generated by Django 5.1.4 on 2025-03-21 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tapAppGestion', '0015_producto_es_barril_producto_litros_disponibles_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='es_barril',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='litros_disponibles',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='litros_por_unidad',
        ),
    ]
