# Generated by Django 5.1.4 on 2025-03-21 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tapAppGestion', '0016_remove_producto_es_barril_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidoproducto',
            name='nota',
            field=models.TextField(blank=True, null=True),
        ),
    ]
