# Generated by Django 5.1.4 on 2025-03-22 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tapAppGestion', '0017_pedidoproducto_nota'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='es_barril',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='producto',
            name='litros_disponibles',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
