# Generated by Django 5.1.4 on 2025-04-01 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tapAppGestion', '0018_producto_es_barril_producto_litros_disponibles'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='kilos_disponibles',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
