# Generated by Django 5.1.4 on 2025-04-04 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tapAppGestion', '0019_producto_kilos_disponibles'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidoproducto',
            name='unidades_pagadas',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
