# Generated by Django 5.1.4 on 2025-04-04 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tapAppGestion', '0020_pedidoproducto_unidades_pagadas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedidoproducto',
            name='unidades_pagadas',
        ),
    ]
