# Generated by Django 5.1.4 on 2025-04-05 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tapAppGestion', '0022_pedidoproducto_impreso_cocina'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedidoproducto',
            name='impreso_cocina',
        ),
    ]
