# Generated by Django 5.1.4 on 2025-04-05 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tapAppGestion', '0023_remove_pedidoproducto_impreso_cocina'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidoproducto',
            name='tiempo',
            field=models.CharField(blank=True, choices=[('I', 'I'), ('II', 'II'), ('III', 'III')], max_length=5, null=True, verbose_name='Tiempo de cocina'),
        ),
    ]
