# Generated by Django 5.1.4 on 2025-04-13 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tapAppGestion', '0024_pedidoproducto_tiempo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedidoproducto',
            name='tiempo',
        ),
        migrations.AddField(
            model_name='registrohorario',
            name='pausado',
            field=models.BooleanField(default=False),
        ),
    ]
