# Generated by Django 5.1.4 on 2025-04-15 14:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tapAppGestion', '0025_remove_pedidoproducto_tiempo_registrohorario_pausado'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrohorario',
            name='tiempo_transcurrido',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
